config/routes.rb
Rails.application.routes.draw do
  resources :dog_breeds, only: [:index] do 
    collection do
      get :fetch_dog_info
    end
  end
  root 'dog_breeds#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dog_breeds_controller.rb
class DogBreedsController < ApplicationController

  def index; end

  def fetch_dog_info
    @dog_image = DogBreed.fetch_image(params[:name]) if params[:name].present?
    if @dog_image["status"] == "success"
      @dog_breed_name = params[:name]
      render json: { dog_breed_name: @dog_breed_name, dog_image: @dog_image["message"] }
    else
      render json: { error: @dog_image["message"] }, status: :unprocessable_entity
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dog_breeds_helper.rb
module DogBreedsHelper
end

app/views/dog_breeds/index.html.erb
<script src="<%= asset_path('custom.js') %>" type="module"></script>
<div class="container mt-5">
	<div class="row">
		  <h1 class="mb-4 text-center text-success">Search your Breed</h1>
		<div class="col-md-6">
		  <%= form_with(url: fetch_dog_info_dog_breeds_path, method: :get, class: 'edit-form', remote: false, id: 'dog-breed-form') do |form| %>
		    <div class="mb-3">
		      <%= form.label :name, class: 'form-label' %>
		      <%= form.text_field :name, class: 'form-control', required: true %>
		    </div>
		    <%= form.submit "Submit", class: 'btn btn-primary', id: 'submit-btn' %>
		  <% end %>
		</div>
      <div class="col-md-6" style="width: 500px; height: 500px;">
		    <div id="dog-breed-result" class="col-md-6"style="width: 100%; height: 100%;">
			    <!-- Dog image will be displayed here -->
			  </div>
	    </div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogBreedApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>